#!/bin/bash

# usercron - https://github.com/jamespo/usercron
set -uo pipefail

USAGE="usercron (help|install|edit <cronfile>)"

USERCRONHOME=$HOME/.config/usercron
UCCMD="${1:-help}"

if [[ ! -d "$USERCRONHOME" ]]; then
    echo "$USERCRONHOME does not exist - exiting"
    exit 1
fi

# distro specific flags
OSUNAME=$(grep -E "^NAME=" /etc/*-release)
if [[ "$OSUNAME" =~ 'Debian' ]]; then
    CRONTESTCMD='crontab'
    CRONTESTFLAG='-n'
elif [[ "$OSUNAME" =~ 'Arch' ]]; then
    # cronie (arch)
    CRONTESTCMD='crontab'    
    CRONTESTFLAG='-T'
else
    # dummy check
    CRONTESTCMD='true'
    CRONTESTFLAG=''
fi

usercron_install () {
    UC_CURR_CRON=$(mktemp)

    FINDENTRIES=$(find "$USERCRONHOME" -type f -name '*.cron' | wc -l)
    if [[ $FINDENTRIES -eq 0 ]]; then
	echo "No cron entries found"
    fi

    # get current cron & remove USERCRON entries
    crontab -l 2>/dev/null > "$UC_CURR_CRON"
    sed -i '/^### USERCRON start .* ###$/,/^### USERCRON end ###$/d' "$UC_CURR_CRON"

    # build USERCRON entries file
    DATE=$(date)
    echo "### USERCRON start $DATE ###" >> "$UC_CURR_CRON"

    if [[ $FINDENTRIES -gt 0 ]]; then
	# loop round cron entries
	cd "$USERCRONHOME" || exit 1
	VALIDENTRIES=0
	for uc_file in *.cron; do
	    CRONTAB_CHECK_TXT=$("$CRONTESTCMD" "$CRONTESTFLAG" "$uc_file" 2>&1)
	    CRONTAB_CHECK=$?
	    if [[ $CRONTAB_CHECK -eq 0 ]]; then
		cat "$uc_file" >> "$UC_CURR_CRON"
		VALIDENTRIES=$((VALIDENTRIES+1))
	    else
		# bad entry
		echo -e "$CRONTAB_CHECK_TXT\n"
	    fi
	done
    else
	VALIDENTRIES=0
    fi

    echo "### USERCRON end ###" >> "$UC_CURR_CRON"

    # overwrite existing crontab
    crontab "$UC_CURR_CRON" >/dev/null

    echo "crontab installed for $USER with $VALIDENTRIES entries from $USERCRONHOME"

    rm "$UC_CURR_CRON"
}

usercron_edit () {
    uc_file="$1"
    cd "$USERCRONHOME" || exit 1
    $EDITOR "$uc_file"

    CRONTAB_CHECK_TXT=$("$CRONTESTCMD" "$CRONTESTFLAG" "$uc_file" 2>&1)
    CRONTAB_CHECK=$?
    if [[ $CRONTAB_CHECK -ne 0 ]]; then
	# bad entry
	echo "$CRONTAB_CHECK_TXT"
	echo "Deleting $uc_file"
	rm "$uc_file"
    else
	echo "Installing $uc_file"
	usercron_install
    fi
}

case "$UCCMD" in
    "help")
	echo "Usage: $USAGE" ;;

    "install")
	usercron_install ;;

    "edit")
	CRONFILE=${2:-}
	if [[ -z "$CRONFILE" ]]; then
	    echo "No cronfile specified"
	    exit 1
	fi
	usercron_edit "$CRONFILE" ;;

    *)
	echo "Usage: $USAGE" ;;
esac

exit 0
